### PR TITLE
Purge IJ1 usage from the IJ2 unit test

### PR DESCRIPTION
**Pull request by ctrueden**
Fix up the IJ2 unit tests to really use only IJ2/ImgLib2 stuff, and no longer use ImageJ1 at all -- i.e., no need to `import ij.*` or `ImageJFunctions` anymore. This is important if you truly want to purge the ImageJ 1.x dependency from your project some day, so that the tests keep working afterward.

Maybe this is interesting, since it shows off how to compute statistics using ops, for example. However, maybe this obfuscates the intermediate step of simply wrapping to/from IJ1 in the test, since it simpler to implement initially. What do you think?

### CODE REVIEW

**Comment by ctrueden** [comment]
@haesleinhuepf @hkmoon Please merge or close.

**Comment by haesleinhuepf** [comment]
Hey @ctrueden ,

wow, I didn't see this PR... for 2 years. Thanks a lot!

@hkmoon : I don't have write-access; would you please merge this? Thanks!

Cheers,
Robert

**Comment by hkmoon** [comment]
@ctrueden I am sorry that it's too late. 
@haesleinhuepf Now you have the permission here. ;)

**Comment by ctrueden** [comment]
Thanks!

**Pull request merged**
